import React, { useState } from 'react';
import { GlobalContext } from '../App';
import { FileText, Download, CheckCircle, Clock, User, Shield } from 'lucide-react';
import { toast } from 'sonner@2.0.3';

interface ReportsProps {
  globalContext: GlobalContext;
}

export default function Reports({ globalContext }: ReportsProps) {
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>('monthly-em');
  const [selectedReport, setSelectedReport] = useState<string | null>(null);

  const templates = [
    { 
      id: 'monthly-em', 
      name: 'Monthly EM Trend Report',
      description: 'Comprehensive monthly environmental monitoring summary with trends and excursions',
      frequency: 'Monthly'
    },
    { 
      id: 'batch-em', 
      name: 'Batch-Specific EM Report',
      description: 'Environmental conditions during batch manufacturing for product disposition',
      frequency: 'Per Batch'
    },
    { 
      id: 'excursion', 
      name: 'Excursion Summary Report',
      description: 'Summary of environmental excursions, investigations, and CAPA',
      frequency: 'On Demand'
    },
    { 
      id: 'micro-trend', 
      name: 'Microbiological Trending',
      description: 'Microbial data trends including seasonal analysis and alert/action limit performance',
      frequency: 'Quarterly'
    },
    { 
      id: 'qualification', 
      name: 'Cleanroom Qualification Report',
      description: 'ISO 14644 classification and requalification documentation',
      frequency: 'Annual / On Demand'
    }
  ];

  const reportHistory = [
    {
      id: 'RPT-2024-0156',
      template: 'Monthly EM Trend Report',
      title: 'Environmental Monitoring - November 2024',
      generatedBy: 'J. Smith',
      generatedDate: '2024-12-01 09:15',
      status: 'Approved',
      approver: 'M. Johnson (QA Manager)',
      approvalDate: '2024-12-02 14:30'
    },
    {
      id: 'RPT-2024-0155',
      template: 'Batch-Specific EM Report',
      title: 'EM Report - Batch 2024-1234',
      generatedBy: 'K. Williams',
      generatedDate: '2024-11-28 16:45',
      status: 'Under Review',
      approver: 'J. Smith (QA Lead)',
      approvalDate: null
    },
    {
      id: 'RPT-2024-0154',
      template: 'Excursion Summary Report',
      title: 'Q4 2024 Excursion Summary',
      generatedBy: 'J. Smith',
      generatedDate: '2024-11-25 11:00',
      status: 'Draft',
      approver: null,
      approvalDate: null
    },
    {
      id: 'RPT-2024-0153',
      template: 'Microbiological Trending',
      title: 'Microbial Trends Q3 2024',
      generatedBy: 'L. Anderson',
      generatedDate: '2024-10-05 10:30',
      status: 'Approved',
      approver: 'M. Johnson (QA Manager)',
      approvalDate: '2024-10-08 13:15'
    }
  ];

  const generateReport = () => {
    const template = templates.find(t => t.id === selectedTemplate);
    toast.success('Report generated', {
      description: `${template?.name} has been generated and saved as draft`
    });
  };

  const approveReport = (reportId: string) => {
    toast.success('Report approved', {
      description: `Report ${reportId} approved with electronic signature`
    });
  };

  const downloadReport = (reportId: string) => {
    const report = reportHistory.find(r => r.id === reportId);
    if (!report) return;
    
    // Create comprehensive PDF content
    const pdfContent = `
========================================
CLEANROOM MONITORING REPORT
========================================

Report ID: ${report.id}
Template: ${report.template}
Title: ${report.title}

Generated By: ${report.generatedBy}
Generated Date: ${report.generatedDate}
Status: ${report.status}
${report.approver ? `Approved By: ${report.approver}` : ''}
${report.approvalDate ? `Approval Date: ${report.approvalDate}` : ''}

========================================
EXECUTIVE SUMMARY
========================================

This report provides a comprehensive analysis of environmental 
monitoring data for the specified period. All critical parameters
were monitored continuously, and deviations were investigated 
according to established procedures.

========================================
ENVIRONMENTAL PARAMETERS MONITORED
========================================

- Particle Counts (0.5µm, 5.0µm)
- Microbial Contamination (Air, Surface, Personnel)
- Temperature (20-22°C)
- Relative Humidity (45-55% RH)
- Differential Pressure (≥10 Pa)
- Airflow Velocity (0.36-0.54 m/s)

========================================
COMPLIANCE SUMMARY
========================================

Total Monitoring Points: 156
Compliant Readings: 152 (97.4%)
Alert Level Excursions: 3 (1.9%)
Action Level Excursions: 1 (0.6%)

========================================
ROOM-BY-ROOM ANALYSIS
========================================

Room 201 - Filling (Grade A)
- ISO Class: 5
- Particle Compliance: 98.2%
- Microbial Compliance: 100%
- HVAC Status: Operational

Room 301 - Aseptic Core (Grade A)  
- ISO Class: 5
- Particle Compliance: 99.1%
- Microbial Compliance: 100%
- HVAC Status: Operational

Room 105 - Weighing (Grade C)
- ISO Class: 7
- Particle Compliance: 96.5%
- Microbial Compliance: 100%
- HVAC Status: Operational

========================================
EXCURSION EVENTS
========================================

${report.template.includes('Excursion') ? 
`DEV-2024-0156 - Particle Count Exceeded Action Limit
Room: Room 201
Value: 3,520 particles/m³ (Limit: 3,500)
Investigation Status: Under Investigation
CAPA: CAPA-2024-089 (Open)

DEV-2024-0155 - Differential Pressure Below Alert
Room: Room 105  
Value: 9.8 Pa (Limit: 10 Pa)
Investigation Status: Closed
Root Cause: Filter loading, replaced per PM schedule

DEV-2024-0154 - Microbial Surface Count Exceeded Action
Room: Room 301
Value: 8 CFU (Limit: 5 CFU)
Investigation Status: Under Investigation  
CAPA: CAPA-2024-088 (Open)` 
: 'No critical excursions during this period'}

========================================
TREND ANALYSIS
========================================

Particle Counts: Stable trend with seasonal variation
Temperature: Within specification, stable
Humidity: Minor fluctuations, all within limits  
Pressure: One excursion due to filter loading

========================================
CORRECTIVE ACTIONS
========================================

1. Filter Replacement Schedule Reviewed
2. Enhanced Pre-operational Monitoring Implemented
3. Staff Retraining on Gowning Procedures Completed

========================================
CONCLUSIONS
========================================

Environmental monitoring during this period demonstrated
overall good control with isolated, investigated excursions.
All deviations were documented and appropriate corrective
and preventive actions were initiated.

========================================
APPROVALS & SIGNATURES
========================================

${report.status === 'Approved' ? 
`Approved By: ${report.approver}
Approval Date: ${report.approvalDate}
Electronic Signature: Verified` 
: 'Pending Approval'}

========================================
END OF REPORT
========================================
Generated: ${new Date().toLocaleString()}
System: Cleanroom Monitoring v2.1
`;

    // Create blob and trigger download
    const blob = new Blob([pdfContent], { type: 'application/pdf' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.id}_${report.template.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    
    toast.success('Report downloaded successfully', {
      description: `${report.id}.pdf (${report.template}) downloaded and ready for review`
    });
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Approved':
        return 'bg-green-100 text-green-700';
      case 'Under Review':
        return 'bg-yellow-100 text-yellow-700';
      case 'Draft':
        return 'bg-gray-100 text-gray-700';
      default:
        return 'bg-gray-100 text-gray-700';
    }
  };

  return (
    <div className="flex gap-6">
      {/* Left - Templates */}
      <div className="w-80 flex-shrink-0">
        <div className="bg-white rounded-lg border border-gray-200 p-4">
          <h3 className="text-gray-900 mb-4">Report Templates</h3>
          <div className="space-y-2">
            {templates.map(template => (
              <div
                key={template.id}
                className={`p-3 border-2 rounded-lg cursor-pointer transition-all ${
                  selectedTemplate === template.id
                    ? 'bg-blue-50 border-blue-500'
                    : 'border-gray-200 hover:border-blue-300'
                }`}
                onClick={() => setSelectedTemplate(template.id)}
              >
                <p className="text-gray-900">{template.name}</p>
                <p className="text-gray-600 mt-1">{template.description}</p>
                <p className="text-gray-500 mt-2">
                  <span className="px-2 py-1 bg-gray-100 rounded text-xs">{template.frequency}</span>
                </p>
              </div>
            ))}
          </div>
        </div>

        {selectedTemplate && (
          <div className="bg-white rounded-lg border border-gray-200 p-4 mt-4">
            <h3 className="text-gray-900 mb-3">Generate Options</h3>
            <div className="space-y-3">
              <div>
                <label className="block text-gray-700 mb-2">Reporting Period</label>
                <select className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500">
                  <option>December 2024</option>
                  <option>November 2024</option>
                  <option>Q4 2024</option>
                  <option>Custom Range</option>
                </select>
              </div>
              <div>
                <label className="block text-gray-700 mb-2">Rooms/Areas</label>
                <select className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500">
                  <option>All Rooms</option>
                  <option>Grade A Areas</option>
                  <option>Grade B Areas</option>
                  <option>Specific Rooms</option>
                </select>
              </div>
              <button
                onClick={generateReport}
                className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                Generate Report
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Center - Report History & Preview */}
      <div className="flex-1">
        <div className="bg-white rounded-lg border border-gray-200 mb-6">
          <div className="border-b border-gray-200 px-6 py-4">
            <h2 className="text-gray-900">Report History</h2>
            <p className="text-gray-600 mt-1">
              Recent and archived regulatory evidence packages
            </p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="px-6 py-3 text-left text-gray-700">Report ID</th>
                  <th className="px-6 py-3 text-left text-gray-700">Title</th>
                  <th className="px-6 py-3 text-left text-gray-700">Template</th>
                  <th className="px-6 py-3 text-left text-gray-700">Generated By</th>
                  <th className="px-6 py-3 text-left text-gray-700">Generated Date</th>
                  <th className="px-6 py-3 text-left text-gray-700">Status</th>
                  <th className="px-6 py-3 text-left text-gray-700">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {reportHistory.map(report => (
                  <tr
                    key={report.id}
                    className="hover:bg-gray-50 cursor-pointer"
                    onClick={() => setSelectedReport(report.id)}
                  >
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <FileText className="w-4 h-4 text-gray-400" />
                        <span className="text-blue-600">{report.id}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-gray-900">{report.title}</td>
                    <td className="px-6 py-4 text-gray-700">{report.template}</td>
                    <td className="px-6 py-4 text-gray-700">{report.generatedBy}</td>
                    <td className="px-6 py-4 text-gray-700">{report.generatedDate}</td>
                    <td className="px-6 py-4">
                      <span className={`px-2 py-1 rounded ${getStatusColor(report.status)}`}>
                        {report.status}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex gap-2">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            downloadReport(report.id);
                          }}
                          className="p-1 hover:bg-gray-100 rounded"
                          title="Download"
                        >
                          <Download className="w-4 h-4 text-gray-600" />
                        </button>
                        {report.status === 'Under Review' && (
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              approveReport(report.id);
                            }}
                            className="p-1 hover:bg-green-100 rounded"
                            title="Approve"
                          >
                            <CheckCircle className="w-4 h-4 text-green-600" />
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Report Preview */}
        {selectedReport && (
          <div className="bg-white rounded-lg border border-gray-200">
            <div className="border-b border-gray-200 px-6 py-4">
              <h2 className="text-gray-900">Report Preview</h2>
              <p className="text-gray-600 mt-1">{selectedReport}</p>
            </div>

            <div className="p-6">
              <div className="border border-gray-300 rounded-lg p-8 bg-white shadow-inner">
                {/* Mock Report Content */}
                <div className="text-center mb-8">
                  <h1 className="text-gray-900 mb-2">Environmental Monitoring Report</h1>
                  <p className="text-gray-700">November 2024</p>
                  <p className="text-gray-600">Plant 1 - Building A</p>
                </div>

                <div className="space-y-6">
                  <div>
                    <h3 className="text-gray-900 mb-2">1. Executive Summary</h3>
                    <p className="text-gray-700">
                      Environmental monitoring for November 2024 showed overall compliance with established limits.
                      Two particle excursions and one microbial action limit were observed and investigated with
                      appropriate corrective actions implemented.
                    </p>
                  </div>

                  <div>
                    <h3 className="text-gray-900 mb-2">2. Classification Status</h3>
                    <table className="w-full border border-gray-300">
                      <thead className="bg-gray-50">
                        <tr>
                          <th className="border border-gray-300 px-4 py-2 text-left text-gray-700">Room</th>
                          <th className="border border-gray-300 px-4 py-2 text-left text-gray-700">Grade</th>
                          <th className="border border-gray-300 px-4 py-2 text-left text-gray-700">ISO Class</th>
                          <th className="border border-gray-300 px-4 py-2 text-left text-gray-700">Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2 text-gray-700">Room 301</td>
                          <td className="border border-gray-300 px-4 py-2 text-gray-700">Grade A</td>
                          <td className="border border-gray-300 px-4 py-2 text-gray-700">ISO 5</td>
                          <td className="border border-gray-300 px-4 py-2 text-green-600">Qualified</td>
                        </tr>
                        <tr>
                          <td className="border border-gray-300 px-4 py-2 text-gray-700">Room 201</td>
                          <td className="border border-gray-300 px-4 py-2 text-gray-700">Grade B</td>
                          <td className="border border-gray-300 px-4 py-2 text-gray-700">ISO 7</td>
                          <td className="border border-gray-300 px-4 py-2 text-green-600">Qualified</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  <div>
                    <h3 className="text-gray-900 mb-2">3. Excursions & Deviations</h3>
                    <p className="text-gray-700 mb-2">Total: 3 events</p>
                    <ul className="list-disc list-inside text-gray-700 space-y-1">
                      <li>DEV-2024-0156: Particle excursion in Room 201 - Under Investigation</li>
                      <li>DEV-2024-0155: Pressure alert in Room 105 - Closed</li>
                      <li>DEV-2024-0154: Microbial action limit in Room 301 - CAPA initiated</li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="text-gray-900 mb-2">4. Conclusion</h3>
                    <p className="text-gray-700">
                      All cleanroom areas maintained their qualified status. Excursions were promptly detected,
                      investigated, and addressed through the deviation and CAPA system. Continuous monitoring
                      and trending indicate stable environmental control.
                    </p>
                  </div>
                </div>

                <div className="mt-8 pt-6 border-t border-gray-300">
                  <p className="text-gray-600 mb-4">Electronic Signatures:</p>
                  <div className="space-y-2">
                    <div className="flex items-center gap-3">
                      <Shield className="w-4 h-4 text-green-600" />
                      <div>
                        <p className="text-gray-900">J. Smith (QA Lead) - Prepared</p>
                        <p className="text-gray-600">2024-12-01 09:15:22 UTC</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <Shield className="w-4 h-4 text-green-600" />
                      <div>
                        <p className="text-gray-900">M. Johnson (QA Manager) - Approved</p>
                        <p className="text-gray-600">2024-12-02 14:30:45 UTC</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Right - Approval & Compliance */}
      {selectedReport && (
        <div className="w-80 flex-shrink-0">
          <div className="bg-white rounded-lg border border-gray-200 p-4 sticky top-24">
            <h3 className="text-gray-900 mb-4">Approval Workflow</h3>
            
            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                </div>
                <div className="flex-1">
                  <p className="text-gray-900">Draft</p>
                  <p className="text-gray-600">J. Smith</p>
                  <p className="text-gray-500">2024-12-01 09:15</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                </div>
                <div className="flex-1">
                  <p className="text-gray-900">Review</p>
                  <p className="text-gray-600">K. Williams (QA)</p>
                  <p className="text-gray-500">2024-12-01 15:30</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                </div>
                <div className="flex-1">
                  <p className="text-gray-900">Approved</p>
                  <p className="text-gray-600">M. Johnson (QA Mgr)</p>
                  <p className="text-gray-500">2024-12-02 14:30</p>
                </div>
              </div>
            </div>

            <div className="mt-6 pt-6 border-t border-gray-200">
              <h4 className="text-gray-900 mb-3">Compliance Check</h4>
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600" />
                  <span className="text-gray-700">21 CFR Part 11</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600" />
                  <span className="text-gray-700">EU Annex 11</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600" />
                  <span className="text-gray-700">ALCOA+ Data Integrity</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600" />
                  <span className="text-gray-700">ISO 14644 Compliance</span>
                </div>
              </div>
            </div>

            <div className="mt-6 pt-6 border-t border-gray-200">
              <h4 className="text-gray-900 mb-3">Distribution</h4>
              <div className="space-y-2 text-gray-700">
                <p>• QA Department</p>
                <p>• Production Management</p>
                <p>• Quality Documentation</p>
                <p>• Regulatory Archives</p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}